version: '3.8'
services:

  phpservermonitor:
    build: .
    image: phpservermonitor:latest
    container_name: phpservermonitor
    restart: always
    environment:
      - TIME_ZONE='Europe/Amsterdam'
      - PSM_REFRESH_RATE_SECONDS=15
      - PSM_AUTO_CONFIGURE=true
      - MYSQL_HOST=db
      - MYSQL_USER=phpservermonitor
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=phpservermonitor
      - MYSQL_DATABASE_PREFIX=psm_
    ports:
      - 8080:80
    volumes:
     - /sessions
    depends_on:
     - db

  db:
    image: mariadb
    container_name: phpservermonitor_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=phpservermonitor
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=phpservermonitor
    volumes:
      - ./mariadb:/var/lib/mysql/phpservermonitor

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpservermonitor_phpmyadmin
  #   restart: always
  #   environment:
  #     - PMA_HOST=db
  #   ports:
  #     - 8081:80
  #   volumes:
  #     - /sessions
